# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listpython.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import pickle
import ast
from random import choice
import sys

def validNum(numString):
    if not numString.isnumeric():
        return False
    size = int(numString)
    if size < 1:
        return False
    return True
        
def initNums(size=24):
    with open('numbers.pickle', 'wb') as f:
        dict = {}
        for i in range(1, size + 1):
            dict[i] = i
        pickle.dump(dict, f, protocol=pickle.HIGHEST_PROTOCOL)

def writeNums(dict):
    with open('numbers.pickle', 'wb') as f:
        pickle.dump(dict, f, protocol=pickle.HIGHEST_PROTOCOL)
        
def readNums():
    with open('numbers.pickle', 'rb') as f:
        dict = pickle.load(f)
        return dict
        
def delNum(key, dict):
    del dict[key]

def restoreNum(key, dict):
    dict[key] = key

def getRand(dict):
    try:
        r = choice(list(dict.values()))
    except IndexError:
        return -1
    delNum(r, dict)
    return r

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(628, 686)
        Dialog.setStyleSheet("QPushButton { }\n"
"qlineargradient(spread:repeat, x1:0.494, y1:0.267, x2:0.495, y2:0.994, stop:0.255682 rgba(248, 0, 0, 255), stop:0.676136 rgba(216, 99, 99, 210))")
        self.numberlabel = QtWidgets.QLabel(Dialog)
        self.numberlabel.setGeometry(QtCore.QRect(380, 20, 221, 541))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(85)
        font.setBold(False)
        font.setWeight(50)
        self.numberlabel.setFont(font)
        self.numberlabel.setAutoFillBackground(False)
        self.numberlabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.numberlabel.setTextFormat(QtCore.Qt.PlainText)
        self.numberlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.numberlabel.setObjectName("numberlabel")
        self.exitButton = QtWidgets.QPushButton(Dialog, clicked= lambda: self.presssave())
        self.exitButton.setGeometry(QtCore.QRect(370, 590, 231, 71))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(18)
        self.exitButton.setFont(font)
        self.exitButton.setStyleSheet("QPushButton { background-color:rgb(92, 250, 150) }")
        self.exitButton.setObjectName("exitButton")
        self.getnumButton = QtWidgets.QPushButton(Dialog, clicked= lambda: self.pressget())
        self.getnumButton.setGeometry(QtCore.QRect(20, 450, 271, 211))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(18)
        font.setKerning(True)
        self.getnumButton.setFont(font)
        self.getnumButton.setStyleSheet("QPushButton { background-color: rgb(27, 235, 228) }")
        self.getnumButton.setObjectName("getnumButton")
        self.initButton = QtWidgets.QPushButton(Dialog, clicked= lambda: self.pressinit())
        self.initButton.setGeometry(QtCore.QRect(20, 30, 271, 101))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.initButton.setFont(font)
        self.initButton.setAutoFillBackground(False)
        self.initButton.setStyleSheet("QPushButton { background-color:rgba(204, 204, 204, 200) }")
        self.initButton.setObjectName("initButton")
        self.restoreButton = QtWidgets.QPushButton(Dialog)
        self.restoreButton.setGeometry(QtCore.QRect(20, 170, 271, 101))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(18)
        self.restoreButton.setFont(font)
        self.restoreButton.setStyleSheet("QPushButton { background-color:rgba(204, 204, 204, 200) }")
        self.restoreButton.setObjectName("restoreButton")
        self.initlineEdit = QtWidgets.QLineEdit(Dialog)
        self.initlineEdit.setGeometry(QtCore.QRect(230, 140, 61, 20))
        self.initlineEdit.setText("")
        self.initlineEdit.setFrame(True)
        self.initlineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.initlineEdit.setObjectName("initlineEdit")
        self.i = QtWidgets.QLabel(Dialog)
        self.i.setGeometry(QtCore.QRect(20, 140, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.i.setFont(font)
        self.i.setObjectName("i")
        self.deleteButton = QtWidgets.QPushButton(Dialog)
        self.deleteButton.setGeometry(QtCore.QRect(20, 310, 271, 101))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(18)
        self.deleteButton.setFont(font)
        self.deleteButton.setStyleSheet("QPushButton { background-color:rgba(204, 204, 204, 200) }")
        self.deleteButton.setObjectName("deleteButton")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 280, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.restorelineEdit = QtWidgets.QLineEdit(Dialog)
        self.restorelineEdit.setGeometry(QtCore.QRect(130, 280, 161, 20))
        self.restorelineEdit.setText("")
        self.restorelineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.restorelineEdit.setObjectName("restorelineEdit")
        self.deltelineEdit = QtWidgets.QLineEdit(Dialog)
        self.deltelineEdit.setGeometry(QtCore.QRect(130, 420, 161, 20))
        self.deltelineEdit.setText("")
        self.deltelineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.deltelineEdit.setObjectName("deltelineEdit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 420, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    numberDict = {}

    try: 
        f = open('numbers.pickle', 'rb')
        numberDict = readNums()
    except:
        initNums()
        numberDict = readNums()

    def pressget(self):
        num = getRand(self.numberDict)
        self.numberlabel.setText(str(num))
        
    def pressinit(self):
        if self.initlineEdit.text()== "":
            initNums()
        elif not validNum(self.initlineEdit.text()):
                self.initlineEdit.setText("")
                return
        else:
            initNums(int(self.initlineEdit.text()))
        self.numberDict = readNums()
        
    def presssave(self):
        writeNums(self.numberDict)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Random List Pop", "Random List Pop"))
        self.numberlabel.setText(_translate("Dialog", ""))
        self.exitButton.setText(_translate("Dialog", "Save to File"))
        self.getnumButton.setText(_translate("Dialog", "Get Random Number"))
        self.initButton.setText(_translate("Dialog", "Create Fresh List"))
        self.restoreButton.setText(_translate("Dialog", "Restore Number"))
        self.i.setText(_translate("Dialog", "(optional) With numbers 1 through:"))
        self.deleteButton.setText(_translate("Dialog", "Delete Number"))
        self.label_2.setText(_translate("Dialog", "Restore number:"))
        self.label_3.setText(_translate("Dialog", "Delete number:"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
